I'm sorry, but an uncaught exception occurred.

While running game code:
<<<<<<< HEAD
  File "renpy/common/00keymap.rpy", line 459, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 459, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 478, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
AttributeError: 'NoneType' object has no attribute 'stores'
=======
  File "game/script.rpy", line 22, in script
    with  trasdos
TypeError: 'Dissolve' object is not callable
>>>>>>> 2c127bfdf575174094745c3986c67da964174bad

-- Full Traceback ------------------------------------------------------------

Full traceback:
<<<<<<< HEAD
  File "renpy/common/00keymap.rpy", line 459, in script
    python hide:
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/ast.py", line 913, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/python.py", line 2111, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 459, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 478, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/loadsave.py", line 392, in save
    roots = renpy.game.log.freeze(None)
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/python.py", line 2008, in freeze
    self.complete(False)
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/python.py", line 1614, in complete
    self.current.stores[name], self.current.delta_ebc[name] = sd.get_changes(begin)
AttributeError: 'NoneType' object has no attribute 'stores'
=======
  File "game/script.rpy", line 22, in script
    with  trasdos
  File "renpy/ast.py", line 1388, in execute
    renpy.exports.with_statement(trans, paired)
  File "renpy/exports.py", line 1640, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2517, in do_with
    clear=clear)
  File "renpy/display/core.py", line 2978, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "renpy/display/core.py", line 3331, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable
>>>>>>> 2c127bfdf575174094745c3986c67da964174bad

