I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script
    with  trasdos
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script
    with  trasdos
  File "renpy/ast.py", line 1388, in execute
    renpy.exports.with_statement(trans, paired)
  File "renpy/exports.py", line 1640, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2517, in do_with
    clear=clear)
  File "renpy/display/core.py", line 2978, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "renpy/display/core.py", line 3331, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

